server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/paymentsDB
    username: usr
    password: pwd
  flyway:
    enabled: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
